# Generated by Django 5.2.11 on 2026-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['portfolio', 'symbol'], name='idx_holding_portfolio_symbol'),
        ),
    ]
