# Generated by Django 5.2.11 on 2026-02-17 15:41

import django.db.models.deletion
import market.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exchange_id', models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase'), ('kraken', 'Kraken'), ('kucoin', 'KuCoin'), ('bybit', 'Bybit')], max_length=50)),
                ('api_key', market.fields.EncryptedTextField(blank=True, default='')),
                ('api_secret', market.fields.EncryptedTextField(blank=True, default='')),
                ('passphrase', market.fields.EncryptedTextField(blank=True, default='')),
                ('is_sandbox', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.CharField(blank=True, default='', max_length=500)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols', models.JSONField(default=list)),
                ('timeframes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('fetch_interval_minutes', models.IntegerField(default=60)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='market.exchangeconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
