# Generated by Django 5.2.11 on 2026-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_orderfillevent_order_avg_fill_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], db_index=True, default='paper', max_length=10),
        ),
    ]
